id: P000740
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:20.798654
source_metadata:
  id: bdr:W3CN6348
  title: སངས་རྒྱས་གཡུང་དྲུང་བོན་གྱི་ཞལ་འདོན་གཅེས་བསྡུས།
  author: ''
  volumes:
    e7bb0cab11974e4aa248f3f9d64b6c22:
      image_group_id: I3CN6350
      title: ''
      volume_number: 1
      total_pages: 360
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
