id: IC3F541B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:57:06+00:00'
last_modified: '2022-06-07T13:36:28.123997+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6348
  title: སངས་རྒྱས་གཡུང་དྲུང་བོན་གྱི་ཞལ་འདོན་གཅེས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9645':
      image_group_id: I3CN6350
      title: ''
      total_pages: 360
      order: 1
      base_file: 9645.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
